%include "loaddll.inc"
%include "frame.inc"

segment .text
global _InitGL33
_InitGL33:
	def_dll_and_load OpenGL32, "opengl32.dll"
	def_dll_func_and_load OpenGL32, glCullFace, "glCullFace"
	def_dll_func_and_load OpenGL32, glFrontFace, "glFrontFace"
	def_dll_func_and_load OpenGL32, glHint, "glHint"
	def_dll_func_and_load OpenGL32, glLineWidth, "glLineWidth"
	def_dll_func_and_load OpenGL32, glPointSize, "glPointSize"
	def_dll_func_and_load OpenGL32, glPolygonMode, "glPolygonMode"
	def_dll_func_and_load OpenGL32, glScissor, "glScissor"
	def_dll_func_and_load OpenGL32, glTexParameterf, "glTexParameterf"
	def_dll_func_and_load OpenGL32, glTexParameterfv, "glTexParameterfv"
	def_dll_func_and_load OpenGL32, glTexParameteri, "glTexParameteri"
	def_dll_func_and_load OpenGL32, glTexParameteriv, "glTexParameteriv"
	def_dll_func_and_load OpenGL32, glTexImage1D, "glTexImage1D"
	def_dll_func_and_load OpenGL32, glTexImage2D, "glTexImage2D"
	def_dll_func_and_load OpenGL32, glDrawBuffer, "glDrawBuffer"
	def_dll_func_and_load OpenGL32, glClear, "glClear"
	def_dll_func_and_load OpenGL32, glClearColor, "glClearColor"
	def_dll_func_and_load OpenGL32, glClearStencil, "glClearStencil"
	def_dll_func_and_load OpenGL32, glClearDepth, "glClearDepth"
	def_dll_func_and_load OpenGL32, glStencilMask, "glStencilMask"
	def_dll_func_and_load OpenGL32, glColorMask, "glColorMask"
	def_dll_func_and_load OpenGL32, glDepthMask, "glDepthMask"
	def_dll_func_and_load OpenGL32, glDisable, "glDisable"
	def_dll_func_and_load OpenGL32, glEnable, "glEnable"
	def_dll_func_and_load OpenGL32, glFinish, "glFinish"
	def_dll_func_and_load OpenGL32, glFlush, "glFlush"
	def_dll_func_and_load OpenGL32, glBlendFunc, "glBlendFunc"
	def_dll_func_and_load OpenGL32, glLogicOp, "glLogicOp"
	def_dll_func_and_load OpenGL32, glStencilFunc, "glStencilFunc"
	def_dll_func_and_load OpenGL32, glStencilOp, "glStencilOp"
	def_dll_func_and_load OpenGL32, glDepthFunc, "glDepthFunc"
	def_dll_func_and_load OpenGL32, glPixelStoref, "glPixelStoref"
	def_dll_func_and_load OpenGL32, glPixelStorei, "glPixelStorei"
	def_dll_func_and_load OpenGL32, glReadBuffer, "glReadBuffer"
	def_dll_func_and_load OpenGL32, glReadPixels, "glReadPixels"
	def_dll_func_and_load OpenGL32, glGetBooleanv, "glGetBooleanv"
	def_dll_func_and_load OpenGL32, glGetDoublev, "glGetDoublev"
	def_dll_func_and_load OpenGL32, glGetError, "glGetError"
	def_dll_func_and_load OpenGL32, glGetFloatv, "glGetFloatv"
	def_dll_func_and_load OpenGL32, glGetIntegerv, "glGetIntegerv"
	def_dll_func_and_load OpenGL32, glGetString, "glGetString"
	def_dll_func_and_load OpenGL32, glGetTexImage, "glGetTexImage"
	def_dll_func_and_load OpenGL32, glGetTexParameterfv, "glGetTexParameterfv"
	def_dll_func_and_load OpenGL32, glGetTexParameteriv, "glGetTexParameteriv"
	def_dll_func_and_load OpenGL32, glGetTexLevelParameterfv, "glGetTexLevelParameterfv"
	def_dll_func_and_load OpenGL32, glGetTexLevelParameteriv, "glGetTexLevelParameteriv"
	def_dll_func_and_load OpenGL32, glIsEnabled, "glIsEnabled"
	def_dll_func_and_load OpenGL32, glDepthRange, "glDepthRange"
	def_dll_func_and_load OpenGL32, glViewport, "glViewport"
	def_dll_func_and_load OpenGL32, wglGetProcAddress, "wglGetProcAddress"
	ret
