%include "loaddll.inc"

%define MATRIX_ASM 1
%include "matrix.inc"

%define _MM_SHUFFLE(fp3,fp2,fp1,fp0) (((fp3) << 6) | ((fp2) << 4) | ((fp1) << 2) | ((fp0)))

import_dll_func memcpy
import_dll_func memset
import_dll_func cos
import_dll_func sin

segment .bss
align 16
global _ZeroVector
_ZeroVector resd 4

segment .text
DefFunc _VectorMultMatrix
	FrameBegin 0, 0

	LoadParam eax, 2

	movaps xmm2, Param(1)
	movaps xmm3, xmm2

	movaps xmm1, xmm2
	shufps xmm1, xmm3, _MM_SHUFFLE(0, 0, 0, 0)
	mulps xmm1, [eax + Matrix.x]
	movaps xmm0, xmm1

	movaps xmm1, xmm2
	shufps xmm1, xmm3, _MM_SHUFFLE(1, 1, 1, 1)
	mulps xmm1, [eax + Matrix.y]
	addps xmm0, xmm1

	movaps xmm1, xmm2
	shufps xmm1, xmm3, _MM_SHUFFLE(2, 2, 2, 2)
	mulps xmm1, [eax + Matrix.z]
	addps xmm0, xmm1

	movaps xmm1, xmm2
	shufps xmm1, xmm3, _MM_SHUFFLE(3, 3, 3, 3)
	mulps xmm1, [eax + Matrix.w]
	addps xmm0, xmm1

	movaps Param(0), xmm0

	FrameEnd
	ret

DefFunc _VectorMultMatrixTransposed
	FrameBegin 20, 2, esi

	lea esi, Variable(4)
	and esi, 0xFFFFFFF0

	LoadParam eax, 2

	movaps xmm1, Param(1)
	mulps xmm1, [eax + Matrix.x]
	movaps [esi + Matrix.x], xmm1
	movaps xmm1, Param(1)
	mulps xmm1, [eax + Matrix.y]
	movaps [esi + Matrix.y], xmm1
	movaps xmm1, Param(1)
	mulps xmm1, [eax + Matrix.z]
	movaps [esi + Matrix.z], xmm1
	movaps xmm1, Param(1)
	mulps xmm1, [eax + Matrix.w]
	movaps [esi + Matrix.w], xmm1

	invoke_cdecl _MatrixTranspose, esi, esi

	movaps xmm0, [esi + Matrix.x]
	movaps xmm1, [esi + Matrix.y]
	addps xmm0, [esi + Matrix.z]
	addps xmm1, [esi + Matrix.w]
	addps xmm0, xmm1

	LoadParam eax, 0
	movaps [eax], xmm0

	FrameEnd
	ret

DefFunc _PreMatRot
	fld dword [eax]
	fld st0
	fcos
	fst dword [edx + 0]
	fsin
	fld st0
	fst dword [edx + 4]
	fchs
	fst dword [edx + 8]
	ret

DefFunc _MatrixIdentity
	FrameBegin 0, 0, edi

	LoadParam edi, 0
	movaps xmm0, [_ZeroVector]
	mov ecx, 4
	xor eax, eax
.fillzero:
	movaps [edi + eax], xmm0
	add al, 16
	loop .fillzero

	mov eax, 0x3F800000
	mov [edi + Matrix.xx], eax
	mov [edi + Matrix.yy], eax
	mov [edi + Matrix.zz], eax
	mov [edi + Matrix.ww], eax

	FrameEnd
	ret

DefFunc _MatrixRotationX
	FrameBegin 3, 1

	invoke_cdecl _MatrixIdentity, Param(0)

	lea eax, Param(1)
	lea edx, Variable(0)
	call _PreMatRot

	LoadParam eax, 0
	mov ecx, Variable(0)
	mov edx, Variable(1)

	mov [eax + Matrix.yy], ecx
	mov [eax + Matrix.yz], edx
	mov [eax + Matrix.zz], ecx
	mov edx, Variable(2)
	mov [eax + Matrix.zy], edx

	FrameEnd
	ret

DefFunc _MatrixRotationY
	FrameBegin 3, 1

	invoke_cdecl _MatrixIdentity, Param(0)

	lea eax, Param(1)
	lea edx, Variable(0)
	call _PreMatRot

	LoadParam eax, 0
	mov ecx, Variable(0)
	mov edx, Variable(1)

	mov [eax + Matrix.xx], ecx
	mov [eax + Matrix.zx], edx
	mov [eax + Matrix.zz], ecx
	mov edx, Variable(2)
	mov [eax + Matrix.xz], edx

	FrameEnd
	ret

DefFunc _MatrixRotationZ
	FrameBegin 3, 1

	invoke_cdecl _MatrixIdentity, Param(0)

	lea eax, Param(1)
	lea edx, Variable(0)
	call _PreMatRot

	LoadParam eax, 0
	mov ecx, Variable(0)
	mov edx, Variable(1)

	mov [eax + Matrix.xx], ecx
	mov [eax + Matrix.xy], edx
	mov [eax + Matrix.yy], ecx
	mov edx, Variable(2)
	mov [eax + Matrix.yx], edx

	FrameEnd
	ret

; void MatrixRotationEuler(Matrix_p out, float yaw, float pitch, float roll)
DefFunc _MatrixRotationEuler ; Generated by gcc
	push ebx
	sub esp, 136
	fld dword [esp+156]
	mov ebx, dword [esp+144]
	fstp qword [esp]
	invoke_dll_func cos
	fstp dword [esp+48]
	fld dword [esp+156]
	fstp qword [esp]
	invoke_dll_func sin
	fstp dword [esp+28]
	fld dword [esp+28]
	fst dword [esp+52]
	fchs
	fstp dword [esp+68]
	fld dword [esp+152]
	fstp qword [esp]
	invoke_dll_func cos
	fstp dword [esp+40]
	fld dword [esp+152]
	fstp qword [esp]
	invoke_dll_func sin
	fstp dword [esp+28]
	fld dword [esp+28]
	fst dword [esp+44]
	fchs
	fstp dword [esp+64]
	fld dword [esp+148]
	fstp qword [esp]
	invoke_dll_func cos
	fstp dword [esp+28]
	fld dword [esp+148]
	fstp qword [esp]
	invoke_dll_func sin
	fstp dword [esp+32]
	fld dword [esp+32]
	fst dword [esp+36]
	fchs
	fstp dword [esp+32]
	fldz
	fld dword [esp+52]
	fld st0
	fmul st0, st2
	fld dword [esp+44]
	fmul st0, st3
	fld dword [esp+40]
	fld st0
	fld dword [esp+48]
	fmul st1, st0
	fxch st1
	fadd st0, st4
	fadd st0, st3
	fadd st0, st6
	fstp dword [esp+80]
	fld st0
	fmul st0, st6
	fadd st5, st0
	fxch st5
	fadd st0, st6
	fstp dword [esp+56]
	fld st1
	fmul st0, st6
	fld dword [esp+64]
	fmulp st2, st0
	fxch st1
	fadd st0, st4
	fadd st0, st1
	fadd st0, st6
	fstp dword [esp+60]
	fxch st3
	fadd st0, st4
	fadd st0, st5
	fstp dword [esp+84]
	fld dword [esp+68]
	fmul st1, st0
	fxch st1
	fadd st0, st4
	fadd st0, st2
	fadd st0, st5
	fstp dword [esp+72]
	fmul st0, st4
	fld dword [esp+48]
	fadd st0, st1
	fadd st0, st5
	fstp dword [esp+48]
	fld dword [esp+52]
	fmul dword [esp+44]
	fadd st0, st4
	fadd st0, st3
	fadd st0, st5
	fxch st1
	faddp st4, st0
	fxch st3
	fadd st0, st4
	fstp dword [esp+76]
	fld st1
	fadd st0, st4
	fld st0
	fld dword [esp+44]
	faddp st2, st0
	fxch st1
	fadd st0, st5
	fstp dword [esp+68]
	fld dword [esp+64]
	fmul st0, st5
	fadd st0, st5
	fld dword [esp+40]
	fadd st0, st1
	fadd st0, st6
	fxch st2
	faddp st3, st0
	fxch st2
	fadd st0, st5
	fstp dword [esp+52]
	fxch st1
	faddp st2, st0
	fxch st1
	fadd st0, st3
	fstp dword [esp+64]
	fld dword [esp+56]
	fmul st0, st3
	fstp dword [esp+100]
	fld dword [esp+60]
	fmul st0, st3
	fstp dword [esp+104]
	fld dword [esp+84]
	fmul st0, st3
	fld dword [esp+80]
	fmul st0, st4
	fld dword [esp+48]
	fmul st0, st5
	fstp dword [esp+96]
	fxch st3
	fst dword [esp+108]
	fmul st0, st4
	fstp dword [esp+124]
	fld dword [esp+76]
	fmul st0, st4
	fstp dword [esp+40]
	fld dword [esp+72]
	fmul st0, st4
	fstp dword [esp+44]
	fld st1
	fmul st0, st4
	fstp dword [esp+120]
	fld dword [esp+68]
	fmul st0, st4
	fld dword [esp+28]
	fld st0
	fmul st0, st6
	fstp dword [esp+88]
	fld dword [esp+36]
	fmul st0, st6
	fstp dword [esp+92]
	fld dword [esp+64]
	fmul st0, st6
	fstp dword [esp+112]
	fld dword [esp+52]
	fmul st0, st6
	fstp dword [esp+116]
	fld dword [esp+80]
	fadd dword [esp+100]
	fld dword [esp+104]
	faddp st1, st0
	fadd st0, st3
	fstp dword [ebx]
	fmul dword [esp+56]
	fadd st0, st4
	fld dword [esp+60]
	fmul dword [esp+32]
	faddp st1, st0
	fadd st0, st2
	fstp dword [ebx+4]
	fld dword [esp+56]
	fmul dword [esp+36]
	fadd st0, st4
	fld dword [esp+60]
	fmul dword [esp+28]
	faddp st1, st0
	faddp st2, st0
	fxch st1
	fstp dword [ebx+8]
	fld dword [esp+100]
	faddp st3, st0
	fxch st2
	fadd dword [esp+104]
	fadd dword [esp+84]
	fstp dword [ebx+12]
	fld dword [esp+72]
	fadd dword [esp+96]
	fld dword [esp+124]
	fadd st1, st0
	fxch st1
	fadd dword [esp+40]
	fstp dword [ebx+16]
	fld dword [esp+28]
	fld dword [esp+48]
	fmul st0, st1
	fadd dword [esp+44]
	fld dword [esp+108]
	fld dword [esp+32]
	fmul st0, st1
	faddp st2, st0
	fxch st1
	fadd dword [esp+40]
	fstp dword [ebx+20]
	fld dword [esp+36]
	fmul dword [esp+48]
	fld dword [esp+44]
	faddp st1, st0
	fxch st1
	fmul st0, st2
	faddp st1, st0
	fadd dword [esp+40]
	fstp dword [ebx+24]
	fld dword [esp+96]
	fadd dword [esp+44]
	faddp st2, st0
	fxch st1
	fadd dword [esp+76]
	fstp dword [ebx+28]
	fld dword [esp+68]
	fld dword [esp+120]
	fadd st1, st0
	fxch st1
	fadd st0, st5
	fstp dword [ebx+32]
	fld dword [esp+88]
	fadd st0, st4
	fld dword [esp+32]
	fmul st0, st4
	faddp st1, st0
	fadd st0, st5
	fstp dword [ebx+36]
	fld dword [esp+92]
	fadd st0, st4
	fxch st3
	fmul st0, st2
	faddp st3, st0
	fxch st2
	fadd st0, st4
	fstp dword [ebx+40]
	fxch st2
	fadd st0, st3
	faddp st1, st0
	fadd st0, st2
	fstp dword [ebx+44]
	fld dword [esp+52]
	fld dword [esp+112]
	fadd st1, st0
	fxch st1
	fadd st0, st3
	fstp dword [ebx+48]
	fld dword [esp+88]
	fld dword [esp+116]
	fadd st1, st0
	fld dword [esp+32]
	fld dword [esp+64]
	fmul st1, st0
	fxch st3
	faddp st1, st0
	fadd st0, st5
	fstp dword [ebx+52]
	fld dword [esp+92]
	fadd st0, st1
	fxch st4
	fmulp st2, st0
	fxch st1
	faddp st3, st0
	fxch st2
	fadd st0, st3
	fstp dword [ebx+56]
	fxch st2
	faddp st1, st0
	faddp st1, st0
	fld1
	fadd
	fstp dword [ebx+60]
	add esp, 136
	pop ebx
	ret

DefFunc _MatrixTranspose
	FrameBegin 0, 0

	LoadParam edx, 0
	LoadParam eax, 1

	movaps xmm3, [eax + Matrix.y]
	movaps xmm1, [eax + Matrix.x]
	shufps xmm1, xmm3, 0x44
	movaps xmm4, xmm1
	movaps xmm1, [eax + Matrix.x]
	shufps xmm1, xmm3, 0xEE
	movaps xmm6, xmm1
	movaps xmm1, [eax + Matrix.z]
	movaps xmm3, [eax + Matrix.w]
	shufps xmm1, xmm3, 0x44
	movaps xmm5, xmm1
	movaps xmm1, [eax + Matrix.z]
	shufps xmm1, xmm3, 0xEE
	movaps xmm7, xmm1

	movaps xmm1, xmm4
	movaps xmm3, xmm5
	shufps xmm1, xmm3, 0x88
	movaps [edx + Matrix.x], xmm1
	movaps xmm1, xmm4
	shufps xmm1, xmm3, 0xDD
	movaps [edx + Matrix.y], xmm1
	movaps xmm1, xmm6
	movaps xmm3, xmm7
	shufps xmm1, xmm3, 0x88
	movaps [edx + Matrix.z], xmm1
	movaps xmm1, xmm6
	shufps xmm1, xmm3, 0xDD
	movaps [edx + Matrix.w], xmm1

	FrameEnd
	ret

